// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VelocityDBAccess
{
    using System.Collections.Generic;
    using System.Reflection;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal partial class CodeTemplate : CodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\nnamespace ");
            
            #line 5 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(NameSpace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    using System;\r\n    using System.Collections.Generic;\r\n    using System.N" +
                    "et;\r\n    using VelocityDb.Session;\r\n");
            
            #line 11 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
 foreach(var lAssemblyName in Schema.LoadedAssembliesNames)
  {
            
            #line default
            #line hidden
            this.Write("    using ");
            
            #line 13 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lAssemblyName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 14 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n /*   public static class ");
            
            #line 16 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("Static\r\n    {\r\n        \r\n");
            
            #line 19 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
 foreach(KeyValuePair<string, string> lPair in Schema.TypesNameToPluralName)
   {
            
            #line default
            #line hidden
            this.Write("        static IEnumerable< ");
            
            #line 21 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lPair.Key));
            
            #line default
            #line hidden
            this.Write(" > IEnumerable< ");
            
            #line 21 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lPair.Key));
            
            #line default
            #line hidden
            this.Write(" >(this ");
            
            #line 21 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lPair.Key));
            
            #line default
            #line hidden
            this.Write(" source)\r\n        {\r\n\t\t\t\t  Session.BeginRead();\r\n\t\t\t\t\treturn Session.AllObjects< " +
                    "");
            
            #line 24 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lPair.Key));
            
            #line default
            #line hidden
            this.Write(" >();\r\n        }\r\n");
            
            #line 26 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("}*/\r\n\r\n    public class ");
            
            #line 29 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        private SessionBase session;\r\n        \r\n");
            
            #line 33 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
 foreach(KeyValuePair<string, string> lPair in Schema.TypesNameToPluralName)
   {
            
            #line default
            #line hidden
            this.Write("        public virtual IEnumerable< ");
            
            #line 35 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lPair.Key));
            
            #line default
            #line hidden
            this.Write(" > ");
            
            #line 35 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lPair.Value));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get\r\n            {\r\n                session.BeginRead();" +
                    "\r\n                return this.session.AllObjects< ");
            
            #line 40 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lPair.Key));
            
            #line default
            #line hidden
            this.Write(" >();\r\n            }\r\n        }\r\n");
            
            #line 43 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
 }
            
            #line default
            #line hidden
            this.Write("\r\n        public void CloseSession()\r\n        {\r\n            if (session.InTransa" +
                    "ction)\r\n\t\t\t\t\t\t\tsession.Commit();\r\n\t\t\t\t\t  session = null;\r\n        }\r\n\r\n        p" +
                    "ublic ");
            
            #line 52 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(TypeName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            session = null;\r\n            bool lPessimistic = Conve" +
                    "rt.ToBoolean(\"");
            
            #line 55 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SessionInfo.PessimisticLocking));
            
            #line default
            #line hidden
            this.Write("\");\r\n            //bool lAuth = Convert.ToBoolean(\"");
            
            #line 56 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SessionInfo.WindowsAuth));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 57 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
          switch (SessionInfo.SessionType)
            {
                case SessionInfo.SessionTypeEnum.NoServerSession:
            
            #line default
            #line hidden
            this.Write("                    session = new SessionNoServer(@\"");
            
            #line 60 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SessionInfo.DBFolder));
            
            #line default
            #line hidden
            this.Write("\", 5000, !lPessimistic);\r\n");
            
            #line 61 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
                  break;
                case SessionInfo.SessionTypeEnum.NoServerSharedSession:
            
            #line default
            #line hidden
            this.Write("                    session = new SessionNoServerShared(@\"");
            
            #line 63 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SessionInfo.DBFolder));
            
            #line default
            #line hidden
            this.Write("\", 5000, !lPessimistic);\r\n");
            
            #line 64 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
                  break;
                case SessionInfo.SessionTypeEnum.ServerClientSession:
            
            #line default
            #line hidden
            this.Write("                    IPHostEntry lHostEntry = Dns.GetHostEntry(@\"");
            
            #line 66 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SessionInfo.Host));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    session = new ServerClientSession(@\"");
            
            #line 67 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SessionInfo.DBFolder));
            
            #line default
            #line hidden
            this.Write("\", lHostEntry.HostName, 2000, !lPessimistic);\r\n");
            
            #line 68 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
                  break;
                default:
            
            #line default
            #line hidden
            this.Write("                    throw new InvalidDataException(\"Invalid Session Type\");\r\n");
            
            #line 71 "G:\VelocityDbSetup\VelocityDB\VelocityDBAccess\CodeTemplate.tt"
                  break;
            }
            
            #line default
            #line hidden
            this.Write("            /*if (session != null)\r\n            {\r\n                SessionBase.Do" +
                    "WindowsAuthentication = lAuth;\r\n            }*/\r\n        }\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    internal class CodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
